import Head from 'next/head'
import login from '../styles/Login.module.css'
import Login from './login/Login'

export default function Home() {
  return (
    <section className={login.login}>
      <Head>
        <title>UserProfile</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Login />

    </section>
  )
}
